/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MagicLinkRouteImport } from './routes/magic-link'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MktRouteImport } from './routes/_mkt'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MktIndexRouteImport } from './routes/_mkt.index'
import { Route as AppOrganizationIdRouteImport } from './routes/app.$organizationId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as MktPricingRouteImport } from './routes/_mkt.pricing'
import { Route as AppOrganizationIdIndexRouteImport } from './routes/app.$organizationId.index'
import { Route as AppOrganizationIdMembersRouteImport } from './routes/app.$organizationId.members'
import { Route as AppOrganizationIdInvitationsRouteImport } from './routes/app.$organizationId.invitations'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const MagicLinkRoute = MagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MktRoute = MktRouteImport.update({
  id: '/_mkt',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MktIndexRoute = MktIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MktRoute,
} as any)
const AppOrganizationIdRoute = AppOrganizationIdRouteImport.update({
  id: '/$organizationId',
  path: '/$organizationId',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const MktPricingRoute = MktPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MktRoute,
} as any)
const AppOrganizationIdIndexRoute = AppOrganizationIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrganizationIdRoute,
} as any)
const AppOrganizationIdMembersRoute =
  AppOrganizationIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppOrganizationIdRoute,
  } as any)
const AppOrganizationIdInvitationsRoute =
  AppOrganizationIdInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AppOrganizationIdRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/pricing': typeof MktPricingRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/$organizationId': typeof AppOrganizationIdRouteWithChildren
  '/': typeof MktIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$organizationId/invitations': typeof AppOrganizationIdInvitationsRoute
  '/app/$organizationId/members': typeof AppOrganizationIdMembersRoute
  '/app/$organizationId/': typeof AppOrganizationIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/pricing': typeof MktPricingRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof MktIndexRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$organizationId/invitations': typeof AppOrganizationIdInvitationsRoute
  '/app/$organizationId/members': typeof AppOrganizationIdMembersRoute
  '/app/$organizationId': typeof AppOrganizationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_mkt': typeof MktRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/_mkt/pricing': typeof MktPricingRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/$organizationId': typeof AppOrganizationIdRouteWithChildren
  '/_mkt/': typeof MktIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$organizationId/invitations': typeof AppOrganizationIdInvitationsRoute
  '/app/$organizationId/members': typeof AppOrganizationIdMembersRoute
  '/app/$organizationId/': typeof AppOrganizationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/app'
    | '/login'
    | '/magic-link'
    | '/pricing'
    | '/admin/customers'
    | '/admin/sessions'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/app/$organizationId'
    | '/'
    | '/admin/'
    | '/app/'
    | '/api/auth/$'
    | '/app/$organizationId/invitations'
    | '/app/$organizationId/members'
    | '/app/$organizationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/magic-link'
    | '/pricing'
    | '/admin/customers'
    | '/admin/sessions'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/'
    | '/admin'
    | '/app'
    | '/api/auth/$'
    | '/app/$organizationId/invitations'
    | '/app/$organizationId/members'
    | '/app/$organizationId'
  id:
    | '__root__'
    | '/_mkt'
    | '/admin'
    | '/app'
    | '/login'
    | '/magic-link'
    | '/_mkt/pricing'
    | '/admin/customers'
    | '/admin/sessions'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/app/$organizationId'
    | '/_mkt/'
    | '/admin/'
    | '/app/'
    | '/api/auth/$'
    | '/app/$organizationId/invitations'
    | '/app/$organizationId/members'
    | '/app/$organizationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MktRoute: typeof MktRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  MagicLinkRoute: typeof MagicLinkRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/magic-link': {
      id: '/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof MagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mkt': {
      id: '/_mkt'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_mkt/': {
      id: '/_mkt/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MktIndexRouteImport
      parentRoute: typeof MktRoute
    }
    '/app/$organizationId': {
      id: '/app/$organizationId'
      path: '/$organizationId'
      fullPath: '/app/$organizationId'
      preLoaderRoute: typeof AppOrganizationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_mkt/pricing': {
      id: '/_mkt/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MktPricingRouteImport
      parentRoute: typeof MktRoute
    }
    '/app/$organizationId/': {
      id: '/app/$organizationId/'
      path: '/'
      fullPath: '/app/$organizationId/'
      preLoaderRoute: typeof AppOrganizationIdIndexRouteImport
      parentRoute: typeof AppOrganizationIdRoute
    }
    '/app/$organizationId/members': {
      id: '/app/$organizationId/members'
      path: '/members'
      fullPath: '/app/$organizationId/members'
      preLoaderRoute: typeof AppOrganizationIdMembersRouteImport
      parentRoute: typeof AppOrganizationIdRoute
    }
    '/app/$organizationId/invitations': {
      id: '/app/$organizationId/invitations'
      path: '/invitations'
      fullPath: '/app/$organizationId/invitations'
      preLoaderRoute: typeof AppOrganizationIdInvitationsRouteImport
      parentRoute: typeof AppOrganizationIdRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MktRouteChildren {
  MktPricingRoute: typeof MktPricingRoute
  MktIndexRoute: typeof MktIndexRoute
}

const MktRouteChildren: MktRouteChildren = {
  MktPricingRoute: MktPricingRoute,
  MktIndexRoute: MktIndexRoute,
}

const MktRouteWithChildren = MktRoute._addFileChildren(MktRouteChildren)

interface AdminRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppOrganizationIdRouteChildren {
  AppOrganizationIdInvitationsRoute: typeof AppOrganizationIdInvitationsRoute
  AppOrganizationIdMembersRoute: typeof AppOrganizationIdMembersRoute
  AppOrganizationIdIndexRoute: typeof AppOrganizationIdIndexRoute
}

const AppOrganizationIdRouteChildren: AppOrganizationIdRouteChildren = {
  AppOrganizationIdInvitationsRoute: AppOrganizationIdInvitationsRoute,
  AppOrganizationIdMembersRoute: AppOrganizationIdMembersRoute,
  AppOrganizationIdIndexRoute: AppOrganizationIdIndexRoute,
}

const AppOrganizationIdRouteWithChildren =
  AppOrganizationIdRoute._addFileChildren(AppOrganizationIdRouteChildren)

interface AppRouteChildren {
  AppOrganizationIdRoute: typeof AppOrganizationIdRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOrganizationIdRoute: AppOrganizationIdRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MktRoute: MktRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  MagicLinkRoute: MagicLinkRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
